//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeMayShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuBaoHanh
    {
        public int MaChiTietPhieuBaoHanh { get; set; }
        public Nullable<int> MaPhieuBaoHanh { get; set; }
        public Nullable<System.DateTime> NgayBaoHanh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuBaoHanh PhieuBaoHanh { get; set; }
    }
}
