//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeMayShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaXe { get; set; }
        public string MauXe { get; set; }
        public int MaPhieuNhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
