//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeMayShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatXe
    {
        public int MaPhieuDatXe { get; set; }
        public Nullable<int> MaXe { get; set; }
        public string MauXe { get; set; }
        public string TenNguoiDat { get; set; }
        public string SDT { get; set; }
        public string TinhTrang { get; set; }
        public System.DateTime NgayDat { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
